language: node_js
node_js:
  - 12
install:
  - npm install
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
script:
  - npm run lint
  - npm run build
cache:
  directories:
    - node_modules
