version: 2.1
orbs:
  node: circleci/node@2.0.1
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          arguments: '--dry-run'
          overwrite: true
          from: dist
          to: 's3://function-diagraph.fanglin.me'
workflows:
  test-and-deploy:
    jobs:
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
      - lint
